### ISSUE TITLE
Consider renaming the project to indicate that it's management API

### ISSUE THREAD

**Issue by prashanthpai** [gluster/python-gluster-mgmt-client#2]
GlusterFS has bindings for:

* I/O operation (libgfapi)
* Management operations

The name `glusterapi-python` can very easily be mistook for I/O bindings especially when libgfapi-python's RPM has been named `python-glusterfs-api`, rightly so, after the C library RPM which is named `glusterfs-api`. Please consider including `mgmt` or `management` word somewhere in the name.

**Comment by prashanthpai** [comment]
Bump!

The sooner the better. There are only 5 contributors and 4 forks currently. Renaming repository at a later stage will cause a larger disruption.

**Comment by phlogistonjohn** [comment]
A couple other variants:
* python-gluster-admin-api
* glusteradmin-api

I like the word "admin" because it's easy to type :-)

Who's "got the power" to make the final decision to implement the rename?

**Comment by sac** [comment]
We will avoid glusteradmin or gluster-admin because there is another project called gadmin, which might cause confusion.

How about `python-glusterd-client', Devyani can change the name once we finalise.
Currently we have just Madhu, Devyani, and John who have forked the project. 
We can request them to reclone.

**Comment by phlogistonjohn** [comment]
> We will avoid glusteradmin or gluster-admin because there is another project called gadmin, which might cause confusion.

Ah. Understandable.

> How about `python-glusterd-client', 

Is "glusterd" widely enough understood as the "management daemon" for this to be discover-able? If so, that's probably OK although I think I'd prefer Prashanth's suggestion of "management" to that. I'll also throw the word "control" into the mix... but that'll be the last synonym I suggest.

> Devyani can change the name once we finalise.
Currently we have just Madhu, Devyani, and John who have forked the project.
We can request them to reclone.

I certainly have no problems re-cloning.

**Comment by sac** [comment]
python-gluster-mgmt-client? It is a bit longer, what do you think?

**Comment by sac** [comment]
Cool then. @Madhu-1  @prashanthpai @aravindavk what do you think about the name? If none of you have any issues, I will request @devyanikota to rename the project.

**Comment by devyanikota** [comment]
Waiting on: @prashanthpai  @aravindavk 
Does "python-gluster-mgmt-client" looks good?
If yes, then  I'll go ahead and change it.

**Comment by prashanthpai** [comment]
@devyanikota Sounds good to me.

**Comment by phlogistonjohn** [comment]
@devyanikota please do!

**Comment by devyanikota** [comment]
Closing this issue. Thanks all.
